apiVersion: v1
kind: Pod
metadata:
  name: sds011-ingest-scheduler
spec:
  restartPolicy: Always
  containers:
    - name: sds011-ingest
      image: chandlernick/sds011-ingest:latest
      imagePullPolicy: Always
      command:
        - /bin/sh
        - -c
        - |
          while true; do
            echo "Running SDS011 ingest at $(date -u)"
            python /app/ingest_sds011.py
            echo "Sleeping 24h..."
            sleep 86400
          done
      volumeMounts:
        - name: raw-data
          mountPath: /data/raw
          subPath: raw
  volumes:
    - name: raw-data
      persistentVolumeClaim:
        claimName: aq-data